### ISSUE TITLE
 Install error 1

### ISSUE THREAD

**Issue by liuqian666** [rrwick/Bandage#104]
Hi，I get in trouble in installing Bandage,and I don't known how to deal with it.
Here are my steps:
sudo apt-get update
sudo apt-get install build-essential git qtbase5-dev libqt5svg5-dev
git clone https://github.com/rrwick/Bandage.git
cd path/to/dir/Bandage
export QT_SELECT=5
qmake
make

then I failed, and the screen showed:
g++: error: /home/epi-linux/miniconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so: No such file or directory
Makefile:692: recipe for target 'Bandage' failed
make: *** [Bandage] Error 1

Did any one known how to solve this problem? 
Thank you very much !

**Comment by D415yAPHA** [comment]
Hi, I am also having the same issue. Has this been resolved yet?

**Comment by rrwick** [comment]
I think that you might also need to `apt install libgl1-mesa-dev` - I just tried building on Ubuntu 20.04, and this worked for me. I'll add it to the README.
