### ISSUE TITLE
Load CSV data - extension request

### ISSUE THREAD

**Issue by jkoszucki** [rrwick/Bandage#105]
Hi @epruesse!

First of all, thank you for such an amazing tool as Bandage. 

Recently I use Bandage a lot and I was thinking if there is a possibility to add an extension to the load CSV data function (or any other), namely to be able to indicate the coordinates of the region within a contig of interest (eg. contig number, start position, end position). 
In my particular case at the moment by coloring the contig I don't know in which particular part of it my sequence occurs. This would allow to avoid relying on the sequence similarity and visualize potential (not known) paths within the graph.

I would be grateful for considering this. It would help me a lot! 

Best,
Janusz

**Comment by epruesse** [comment]
@jkoszucki - I wrote the csv import several years ago, but that was my only contribution to Bandage, I'm not the author, I just wanted to add in some data of mine back then. You probably want @rrwick's help here. I don't even know what he's done with the code in the mean time, and I am way behind on feature-requests/bug-reports  on my own (un)published tools...

**Comment by jkoszucki** [comment]
@epruesse, thank you for quick response. I completely understand that, especially that last changes in code were done few years ago. Nevertheless, thanks for response!
