### ISSUE TITLE
Command line drawing

### ISSUE THREAD

**Issue by mariokostelac** [rrwick/Bandage#14]
Hi,

is there a way to get the graph drawn without booting up GUI?
I usually run assemblies on server machines without GUI installed and I'd like to have it as part of a pipeline.

**Comment by rrwick** [comment]
Yes, Bandage can be run from the command line, and the 'Bandage image' command will generate an image file without ever opening a GUI.

Take a look here for some documentation and example commands:
[github.com/rrwick/Bandage/wiki/Command-line](https://github.com/rrwick/Bandage/wiki/Command-line)

What may be trickier is getting Bandage to run on your server.  Your server is running Linux, I assume?  I'd suggest trying the statically-linked Linux build I've put [on GitHub here](https://github.com/rrwick/Bandage/releases).  That was built on Ubuntu 14.04, so whether or not it will work may depend on how similar your Linux distro is to Ubuntu.  If it doesn't work, you can try building Bandage from source, the difficulty of which may again depend on your distribution.  If you run into issues, please let me know and I'll do my best to help.

**Comment by mariokostelac** [comment]
Ah, no problems with that. I am packing my software in Docker containers so I can prepare everything upfront and install anything I need. Thanks for the answer!
