### ISSUE TITLE
Is right mouse button meant to do stuff?

### ISSUE THREAD

**Issue by tseemann** [rrwick/Bandage#15]
I installed the latest version on OS X (El Capitan) and it all works great but right mouse button doesn't do anything. Should it be?

**Comment by rrwick** [comment]
The right mouse button doesn't do a lot, but it has a couple of functions:
* Clicking and dragging a node using the right mouse button will only move one piece of it at a time - useful for fine-tuning node shape.
* Holding command and then right-click dragging on the background will rotate the scene.

Are those functions still working?  I haven't upgraded yet myself.

**Comment by tseemann** [comment]
*I haven't upgraded yet myself.*

Hahaha - time to "eat your own dogfood" as they say at Amazon!

**Comment by andersgs** [comment]
I should add that selecting multiple nodes with cntr+click seems broken too. Same machine specs as Torsten.

**Comment by rrwick** [comment]
I'm now using El Capitan myself, and I'm afraid that I can't reproduce any of these issues - it's all working for me as it's supposed to...

Anders, are you using command-click instead of ctrl-click?  The Mac version of Bandage uses command where other OS versions use ctrl.

**Comment by andersgs** [comment]
Sorry, Ryan. Command-click works. Thank you.
