### ISSUE TITLE
BLAST hit labels showing double

### ISSUE THREAD

**Issue by rec3141** [rrwick/Bandage#19]
Any idea what's going on here?

![image](https://cloud.githubusercontent.com/assets/1102883/13622312/4de33c6c-e54a-11e5-9f76-7795ec5f0f97.png)

ps thanks for a great program -- I've been looking for it for ages!

**Comment by rrwick** [comment]
I suspect that each of those nodes in the graph has two separate BLAST hits from two different queries.  It looks like one contains 'cds_gene' in the name and the other 'Sfri_0436', or something like that - it was a challenge to read!

If that is the case, then this is 'normal' behaviour, if a bit messy.  At the bottom left part of the UI is a 'Query' drop-down menu where you can choose which BLAST query to look at.  It's currently set to 'all' so it's showing all at once.  You should be able to choose just one to look at, which will clean it up.

Alternatively, in the BLAST window and in the queries table, you can untick one of those two queries to hide it in the visualisation.  Or if they are totally redundant (maybe one is a nucleotide sequence and the other is the corresponding protein sequence), you can just remove one of the queries by selecting it in the table and clicking 'Clear selected'.

Let me know if that fixes the issue!  If not, I'll do my best to troubleshoot further.

And in general, I have found that long BLAST query names make for messy labels on the graph.  So it can help to rename the queries to something shorter.  You can do that in Bandage by double-clicking the query name in the queries table.  Or if you're using the same queries again and again, it might be easier to rename them in the FASTA file.  When Bandage loads BLAST queries from a FASTA file, it names them using everything up to the first space in the header line.

**Comment by rec3141** [comment]
Thanks for your quick response. I see now that when I did "Load from FASTA file" it doesn't replace the contents but adds to it. I cleared all and it re-added and now it works great. And thanks for the tip about the names!
