### ISSUE TITLE
Can annotation GFF3 be loaded?

### ISSUE THREAD

**Issue by suryasaha** [rrwick/Bandage#20]
Is it possible to load a GFF3 with the annotation of the assembly into Bandage? The idea would be to analyze regions in the graph corresponding to certain genomic features. Thanks

**Comment by rrwick** [comment]
Unfortunately, no - Bandage doesn't really support any kind of sequence annotation. It would be a cool feature, but a lot to develop. Realistically, I probably won't be adding it any time soon.

However, you can sort of mimic annotation by using a BLAST search. If you have a FASTA file of the sequences (nucleotide or protein) for your features, you can use them as BLAST queries. The resulting BLAST hits will be visualised on the graph, allowing you to examine the relevant graph regions.

If you know that the query sequences are definitely in your graph and you only want very good BLAST hits (i.e. not homologous sequences elsewhere in the graph), I'd recommend using some of the BLAST filters like for length and identity.

Hope this helps! Let me know know if I can clarify further.

**Comment by suryasaha** [comment]
That is a good workaround. I will give it a shot. Thanks
