### ISSUE TITLE
'explode' nodes

### ISSUE THREAD

**Issue by flashton2003** [rrwick/Bandage#26]
Hi Ryan,

I love bandage, so thanks for that!

However, sometimes it can be quite difficult to see what is going on. e.g. 
![screen shot 2016-07-08 at 15 15 16](https://cloud.githubusercontent.com/assets/2613906/16690209/cb3467f2-451e-11e6-8700-6d71f0eecc0a.png)

what would be great is if there were an 'explode' or 'repel' function that made the nodes all spread apart, kind of like this

![screen shot 2016-07-08 at 15 17 17](https://cloud.githubusercontent.com/assets/2613906/16690297/189d4482-451f-11e6-8163-890df2bfe3db.png)

 I have no idea how difficult it would be to do that, but i think it would be quite useful.

Thanks again for developing a great tool.

**Comment by rrwick** [comment]
That feature already exists (sort of), as of the latest version (v0.8.0). If you go to the settings (`Bandage -> Preferences` on a Mac, `Tools -> Settings` on Linux/Windows), then you should see an option near the top called `Edge length`. If you turn that way up and then redraw the graph, the nodes should separate much like you've shown.

To be clear though, this setting affects the graph layout step, so it won't explode your current layout - you'll need to click `Draw graph` to see the effects. And of course very dense/tangled areas can be difficult to interpret, even when the nodes are spaced. So in really nasty cases you'll probably have to strategically choose which nodes are displayed by altering the `Scope`.

**Comment by flashton2003** [comment]
Cool, will check it out.
