### ISSUE TITLE
GFA 2

### ISSUE THREAD

**Issue by sjackman** [rrwick/Bandage#30]
Hi, Ryan. Have you had a chance to look at the nearly finalized GFA 2 spec?
See https://github.com/thegenemyers/GFA-spec/blob/master/GFA2-spec.md
and https://github.com/GFA-spec/GFA-spec/pull/48

**Comment by rrwick** [comment]
I just took a look right now and commented on the main thread. It's looking good! I don't have any changes to suggest and I think I could put this format to good use in my [current project](https://github.com/rrwick/Unicycler).

**Comment by sjackman** [comment]
Awesome and glad to hear it! I'll check out Unicycler too. Great name.

**Comment by ylipacbio** [comment]
@rrwick 
Bandage is an awesome assembly visualization tool.
I am wondering if you plan to support GFA2 in bandage? (If yes, what is the time line?)
Thank you.

**Comment by sjackman** [comment]
Any thoughts on implementing GFA2, Ryan? Support only the two necessary record types `L` and `E` should be pretty straight forward. It'd be a big step forward in helping the adoption of GFA2.

Here's a small graph in both GFA1 and GFA2: [test.gfa1.gz](https://github.com/rrwick/Bandage/files/1732642/test.gfa1.gz) [test.gfa2.gz](https://github.com/rrwick/Bandage/files/1732643/test.gfa2.gz)
https://gist.github.com/sjackman/2f09429b255f864b5fe8a966b39af63f
