### ISSUE TITLE
/usr/include shouldn't be in INCLUDEPATH

### ISSUE THREAD

**Issue by Piezoid** [rrwick/Bandage#36]
Using GCC 6.3.1 and Qt 5.8.0 on ArchLinux, compilation failed with :
> fatal error: stdlib.h: No such file or directory

The error is related to [QTBUG-53367](https://bugreports.qt.io/browse/QTBUG-53367). The bug report mention GCC 6.1.0 and Qt 5.6.0. The conclusion is that :

> the problem are the broken qmake-based build systems of 3rd party applications, which somehow end up adding /usr/include to INCLUDEPATH. report bugs against these applications.
fix for them:
    MY_EXTERNAL_INCLUDES -= $$QMAKE_DEFAULT_INCDIRS
    INCLUDEPATH += $$MY_EXTERNAL_INCLUDES
note that -L switches added to LIBS also need filtering based on QMAKE_DEFAULT_LIBDIRS.

A quick git blame on the .pro reported no obvious reason for adding /usr/include to INCLUDEPATH (it's there since the initial commit)

**Comment by rrwick** [comment]
It's been so long since I first made that project, I have no idea why that was there! I've removed it and push the change to the development branch (https://github.com/rrwick/Bandage/commit/109c3cb6935f5d1c7f88e627b84fec5a2b2ee362), which should make its way into the next release. Thanks!

**Comment by yukon456** [comment]
Gritty was here
