### ISSUE TITLE
When loading files, remember directory -- or add command-line argument

### ISSUE THREAD

**Issue by rchikhi** [rrwick/Bandage#4]
Would be great is Bandage could remember the folder of the last opened file, so that File->Load directly goes to it, instead of $HOME. Alternatively, "./Bandage file.fasta" could work too. Right now, it's a time-waster to navigate to the right folder whenever I want to reload a file.

**Comment by rrwick** [comment]
I assume you mean to remember the folder between sessions?  Bandage does currently remember the folder within a session.  I'll look into adding that feature.

However, your alternative was pretty easy to implement, so I added that.  You can now call Bandage with a command line argument, like in your example.  If it points to a file that Bandage knows how to load, it will load it on start-up.

I'm creating a new Bandage release now that includes this feature (and a few other bug fixes).

**Comment by rchikhi** [comment]
Excellent! thanks for the very quick response
