### ISSUE TITLE
Crash on a small FastG file

### ISSUE THREAD

**Issue by rchikhi** [rrwick/Bandage#5]
This small FastG crashes Bandage with a segfault when I draw the graph. Is it malformed? (assembled with k=21, exact overlaps of length 20)

```
>NODE_0_length_415_cov_0_ID_0;
CTCTAATAGGACCTCTTGCCCATCCGAGGCTTAAGCAGCGACTCCACATGGAGCGATGGGTCCTCAAGGC
AGTATAAAATGGACTGCTATCTAGGCGTTAAAGTAGTAGAACGAGGGTCGGGCGATTTGTTTTGGTAGTG
GTTATCGCATTGCAAGAACGTACGGACGGACAAAATGTCGGACACCGCCTTATCGGCTATACTAGTTAGA
GCCTCGCTTGGGTCTCTACATCCGCTGATACGCGCGAGCTCTCACCCACGACTGTACCCCGGTTAAGATT
TATAAACCATACATTTAACCCTTAGTCATAAGATGATACTTCATCTGCATGCGCGCATCTTCCTATTTTA
TGGTCTTAATTGAGTGTTCAGAGTTGGGGGTCACAGATGAGCGTTCCGATTGTCCTTTCCCAGGC
>NODE_0_length_415_cov_0_ID_0':NODE_29_length_41_cov_0_ID_29';
GCCTGGGAAAGGACAATCGGAACGCTCATCTGTGACCCCCAACTCTGAACACTCAATTAAGACCATAAAA
TAGGAAGATGCGCGCATGCAGATGAAGTATCATCTTATGACTAAGGGTTAAATGTATGGTTTATAAATCT
TAACCGGGGTACAGTCGTGGGTGAGAGCTCGCGCGTATCAGCGGATGTAGAGACCCAAGCGAGGCTCTAA
CTAGTATAGCCGATAAGGCGGTGTCCGACATTTTGTCCGTCCGTACGTTCTTGCAATGCGATAACCACTA
CCAAAACAAATCGCCCGACCCTCGTTCTACTACTTTAACGCCTAGATAGCAGTCCATTTTATACTGCCTT
GAGGACCCATCGCTCCATGTGGAGTCGCTGCTTAAGCCTCGGATGGGCAAGAGGTCCTATTAGAG
>NODE_29_length_41_cov_0_ID_29:NODE_0_length_415_cov_0_ID_0;
ATTTAGACCGTTCACTGAACCCTCTAATAGGACCTCTTGCC
>NODE_29_length_41_cov_0_ID_29';
GGCAAGAGGTCCTATTAGAGGGTTCAGTGAACGGTCTAAAT
```

**Comment by rrwick** [comment]
The problem is the first node is numbered 0 and the second, its complement, is -0.  I'm not exactly sure where this is upsetting Bandage, but when I rename them to 1 and -1, it works.

Did this FASTG come from SPAdes?  I've only ever loaded SPAdes FASTG files in Bandage, and I haven't encountered this before.

**Comment by rchikhi** [comment]
Hi, oh I see. No, not from SPAdes, my own fasta2fastg implementation.

**Comment by tseemann** [comment]
@rchikhi it would be neat if your "fasta2fastg" tool could take an arbitray contigs file and *magically infer* the original graph it came from :-)

**Comment by rrwick** [comment]
The current version of Bandage (v0.6.0) now uses string-based node IDs instead of integers, which makes this problem go away.  Your sample file can now load without a crash.
