### ISSUE TITLE
Copy node to clipboard button

### ISSUE THREAD

**Issue by alexjironkin** [rrwick/Bandage#7]
Hi,

I just noticed thst copy node to clipboard/save to fasta have disappeared. It was really useful to have and see them visually. Only after diggin in menus I noticed that I could use short cuts.

Please bring buttons back. It was really useful to have them visible on the right pane.

**Comment by rrwick** [comment]
Hmmm, I had felt as though the main UI was getting a bit cluttered, so when I added the 'Select' menu, I moved the 'Copy to clipboard' and 'Save to FASTA' functions up there.  If they are missed, though, I can bring the buttons back in the next release.

**Comment by rrwick** [comment]
Alex,
I'm sorry, but as I add more features to Bandage I worry about UI clutter, so I've decided to leave these functions in the menu.  I'm going to close this issue now.
Ryan
