### ISSUE TITLE
 Bandage line command cannot interpret colour scheme from GFA file #95 

### ISSUE THREAD

**Issue by alvipal** [rrwick/Bandage#96]
Hi, 

When I launch Unicycler, I get a GFA graph that I visualize with Bandage. 
The colors of the nodes are determined inside the GFA file  (sample attached in the image)
If I open Bandage via the interface, it interprets the colours perfectly. But it's not the same if I launch it via

`Bandage image my_graph.gfa imagen.png --toutline 1 --names --fontsize 8`

**Which command should I use on the shell to achieve Bandage could to interpret the color specified inside the GFA file?**

Screenshoot of the inside of GFA file, which include the specification of the node colours:
![custom_colours_inside_gfa_file](https://user-images.githubusercontent.com/24392380/90006357-04642380-dc99-11ea-9d3f-c32a04a061e5.png)

Bandage GUI capable of interpreting the GFA colours:
![graph_bandage_GUI](https://user-images.githubusercontent.com/24392380/90006419-2067c500-dc99-11ea-8725-5b4fe12f2b4f.png)

Bandage command is NOT able to interpretate the GFA colours:
`Bandage image my_graph.gfa imagen.png --toutline 1 --names --fontsize 8`
![imagen](https://user-images.githubusercontent.com/24392380/90007092-66715880-dc9a-11ea-9d13-0ddcd1428206.png)

**Which command should I use on the shell to achieve Bandage could to interpret the color specified inside the GFA file?**

Thanks a lot in advance!!!

**Comment by rrwick** [comment]
Using `--colour custom` option should make Bandage use the colours in the GFA file. This is currently only in the development branch, but I will make a new release with this fix shortly.
